version: '3.9'

services:
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
#    environment:
#      - DJANGO_SETTINGS_MODULE=WorkBench.settings
volumes:
  static_volume:
